/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UISplitAndMaskView : UIView

- (id)initWithImage:(id)arg1 visibleTopHeight:(double)arg2 visibleBottomHeight:(double)arg3;

@end
