/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarLiquidDetectionItemView : UIStatusBarItemView

- (id)accessibilityHUDRepresentation;
- (id)contentsImage;

@end
