/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarStudentItemView : UIStatusBarIndicatorItemView

- (id)accessibilityHUDRepresentation;

@end
