/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarCarPlayItemView : UIStatusBarIndicatorItemView

- (id)accessibilityHUDRepresentation;

@end
