/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UITextMagnifierRangedRenderer : UITextMagnifierCommonRenderer

- (id)visualsForMagnifier;

@end
